version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ericson
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: realtime
    ports:
      - "1234:5432"
    restart: always
volumes:
  postgres-db-volume:

